// src/utils/fallback.ts
import type { BlogPost, TeachingPost } from '@/types';

const FALLBACK_IMG = '/assets/fallback-blog.jpeg';

// ---- BLOG FALLBACKS (no `updatedAt` on BlogPost) ----
export const FALLBACK_BLOGS: BlogPost[] = [
  {
    id: 'fb-1',
    title: 'Why Media Literacy Still Matters',
    author: 'Dr Odera Ezenna',
    summary: 'Spotting bias, sourcing, and context.',
    image: FALLBACK_IMG,
    content: 'In a world of infinite feeds, literacy means interrogating sources…',
    createdAt: new Date().toISOString(),
    // notified is optional in your UI types; omit unless required
  },
  {
    id: 'fb-2',
    title: 'Teaching With Stories',
    author: 'Dr Odera Ezenna',
    summary: 'Narrative as a scaffold for complex topics.',
    image: FALLBACK_IMG,
    content: 'Stories give learners an anchor. Start with lived examples…',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fb-3',
    title: 'The Newspaper Aesthetic',
    author: 'Dr Odera Ezenna',
    summary: 'Serifs, columns, rhythm.',
    image: FALLBACK_IMG,
    content: 'Design guides attention. Headlines set hierarchy; whitespace breathes…',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fb-4',
    title: 'Research Routines',
    author: 'Dr Odera Ezenna',
    summary: 'Batch reading, annotation, synthesis.',
    image: FALLBACK_IMG,
    content: 'Block time: skim → deep read → synthesize. Habits win…',
    createdAt: new Date().toISOString(),
  },
];

// ---- TEACHING FALLBACKS (TeachingPost DOES have `updatedAt`) ----
export const FALLBACK_TEACHING: TeachingPost[] = [
  {
    id: 'ft-1',
    title: 'Media & Society 101',
    school: 'City University',
    year: '2024',
    type: 'Lecture',
    isCurrent: false,
    tags: ['media', 'society', 'theory'],
    description: 'Foundations of media theory, bias, and representation.',
    fullText: 'Syllabus overview, weekly topics, assessment structure…',
    startDate: undefined,
    endDate: undefined,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    notified: false,
  },
  {
    id: 'ft-2',
    title: 'Qualitative Methods Lab',
    school: 'Kingston College',
    year: '2023',
    type: 'Seminar',
    isCurrent: false,
    tags: ['methods', 'qualitative'],
    description: 'Interviews, coding transcripts, thematic maps.',
    fullText: 'Practice sessions, coding frameworks, sample assignments…',
    startDate: undefined,
    endDate: undefined,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    notified: false,
  },
  {
    id: 'ft-3',
    title: 'Writing for Public Scholarship',
    school: 'Open Learning Institute',
    year: '2022',
    type: 'Workshop',
    isCurrent: false,
    tags: ['writing', 'public'],
    description: 'Turn research into op-eds and accessible essays.',
    fullText: 'Pitching, structure, voice, and editorial feedback…',
    startDate: undefined,
    endDate: undefined,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    notified: false,
  },
  {
    id: 'ft-4',
    title: 'Media Histories',
    school: 'Riverside University',
    year: '2021',
    type: 'Lecture',
    isCurrent: false,
    tags: ['history', 'technology'],
    description: 'From print to platform: tech that reshaped discourse.',
    fullText: 'Timelines, key movements, and primary sources…',
    startDate: undefined,
    endDate: undefined,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    notified: false,
  },
];
